apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: test-ns
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'mongodb-exporter'
        static_configs:
          - targets: ['mongodb-exporter-service.test-ns.svc.cluster.local:9216']

