apiVersion: v1
kind: Service
metadata:
  name: spark-pi-metrics
  namespace: spark-jobs
  labels:
    app: spark-pi-scheduled
spec:
  ports:
  - name: metrics
    port: 8090
    targetPort: 8090
  selector:
    app: spark-pi-scheduled
